# Generated by Django 2.2.7 on 2019-11-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pprice',
            field=models.IntegerField(default=0),
        ),
    ]
